---
title: "EmployeeSurveyAssignment"
author: "Jessica Qian"
date: "2026-09-19"
output: html_document
---

```{r}
library(readxl)

Typical_Employee_Survey_Data_1_ <- read_excel("Typical_Employee_Survey_Data (1).xlsx")
```

#Renaming Columns
```{r}
names(Typical_Employee_Survey_Data_1_)[1] <- "Age"
names(Typical_Employee_Survey_Data_1_)[2] <- "Gender"
names(Typical_Employee_Survey_Data_1_)[3] <- "Satisfaction"
names(Typical_Employee_Survey_Data_1_)[4] <- "Characteristics"
names(Typical_Employee_Survey_Data_1_)[5] <- "Years Worked"
names(Typical_Employee_Survey_Data_1_)[6] <- "Promotion Likelihood"
names(Typical_Employee_Survey_Data_1_)[7] <- "Decision-Making"
names(Typical_Employee_Survey_Data_1_)[8] <- "Budgetary Decisions"
names(Typical_Employee_Survey_Data_1_)[9] <- "Pride"
names(Typical_Employee_Survey_Data_1_)[10] <- "Reject Other Jobs"
names(Typical_Employee_Survey_Data_1_)[11] <- "Relations"
```

#Str Check
str(Typical_Employee_Survey_Data_1_)

###5-Point Summary & Boxplot BEFORE Changing Factor
```{r}
summary(Typical_Employee_Survey_Data_1_$Age)
summary(Typical_Employee_Survey_Data_1_$Gender)
summary(Typical_Employee_Survey_Data_1_$Satisfaction)
summary(Typical_Employee_Survey_Data_1_$Characteristics)
summary(Typical_Employee_Survey_Data_1_$`Years Worked`)
summary(Typical_Employee_Survey_Data_1_$`Promotion Likelihood`)
summary(Typical_Employee_Survey_Data_1_$`Decision-Making`)
summary(Typical_Employee_Survey_Data_1_$`Budgetary Decisions`)
summary(Typical_Employee_Survey_Data_1_$Pride)
summary(Typical_Employee_Survey_Data_1_$`Reject Other Jobs`)
summary(Typical_Employee_Survey_Data_1_$Relations)

boxplot(Typical_Employee_Survey_Data_1_$Age)
boxplot(Typical_Employee_Survey_Data_1_$Gender)
boxplot(Typical_Employee_Survey_Data_1_$Satisfaction)
boxplot(Typical_Employee_Survey_Data_1_$Characteristics)
boxplot(Typical_Employee_Survey_Data_1_$`Years Worked`)
boxplot(Typical_Employee_Survey_Data_1_$`Promotion Likelihood`)
boxplot(Typical_Employee_Survey_Data_1_$`Decision-Making`)
boxplot(Typical_Employee_Survey_Data_1_$`Budgetary Decisions`)
boxplot(Typical_Employee_Survey_Data_1_$Pride)
boxplot(Typical_Employee_Survey_Data_1_$`Reject Other Jobs`)
boxplot(Typical_Employee_Survey_Data_1_$Relations)

```

#Factor Change

```{r}
Typical_Employee_Survey_Data_1_$Gender <- factor(Typical_Employee_Survey_Data_1_$Gender,
levels = c(1, 2),
labels = c("M", "F"))

Typical_Employee_Survey_Data_1_$Satisfaction <- factor(Typical_Employee_Survey_Data_1_$Satisfaction,
levels = c(1, 2, 3, 4),
labels = c("Very Satisfied", "Moderately Satisfied", "A Little Dissatisfied", "Very Dissatisfied"))

Typical_Employee_Survey_Data_1_$Characteristics <- factor(Typical_Employee_Survey_Data_1_$Characteristics,
levels = c(1,2,3,4,5),
labels = c("High Income", "No Danger of Being Fired", "Flexible Hours","Opportunities for Advancement", "Enjoy the Work"))

Typical_Employee_Survey_Data_1_$`Promotion Likelihood` <- factor(Typical_Employee_Survey_Data_1_$`Promotion Likelihood`,
levels = c(1,2,3,4,5),
labels = c("Very Likely", "Likely","Not Sure","Unlikely","Very Unlikely"))

Typical_Employee_Survey_Data_1_$`Decision-Making` <- factor(Typical_Employee_Survey_Data_1_$`Decision-Making`,
levels = c(1,2,3,4),
labels = c("Always", "Much of the time","Sometimes","Never"))

Typical_Employee_Survey_Data_1_$`Budgetary Decisions` <- factor(Typical_Employee_Survey_Data_1_$`Budgetary Decisions`,
levels = c(1,2),
labels = c("Yes", "No"))

Typical_Employee_Survey_Data_1_$Pride <- factor(Typical_Employee_Survey_Data_1_$Pride,
levels = c(1,2,3,4),
labels = c("Very Proud", "Somewhat Proud","Indifferent","Not At All Proud"))

Typical_Employee_Survey_Data_1_$`Reject Other Jobs` <- factor(Typical_Employee_Survey_Data_1_$`Reject Other Jobs`,
levels = c(1,2,3,4,5),
labels = c("Very Likely", "Likely","Not Sure","Unlikely","Very Unlikely"))

Typical_Employee_Survey_Data_1_$Relations <- factor(Typical_Employee_Survey_Data_1_$Relations,
levels = c(1,2,3,4,5),
labels = c("Very Good", "Good","So So","Bad","Very Bad"))
```



###5-Point Summary & Boxplot AFTER Changing Factor

```{r}
str(Typical_Employee_Survey_Data_1_)
summary(Typical_Employee_Survey_Data_1_)
summary(Typical_Employee_Survey_Data_1_$Age)
summary(Typical_Employee_Survey_Data_1_$Gender)
summary(Typical_Employee_Survey_Data_1_$Satisfaction)
summary(Typical_Employee_Survey_Data_1_$Characteristics)
summary(Typical_Employee_Survey_Data_1_$`Years Worked`)
summary(Typical_Employee_Survey_Data_1_$`Promotion Likelihood`)
summary(Typical_Employee_Survey_Data_1_$`Decision-Making`)
summary(Typical_Employee_Survey_Data_1_$`Budgetary Decisions`)
summary(Typical_Employee_Survey_Data_1_$Pride)
summary(Typical_Employee_Survey_Data_1_$`Reject Other Jobs`)
summary(Typical_Employee_Survey_Data_1_$Relations)
boxplot(Typical_Employee_Survey_Data_1_$Age)
boxplot(Typical_Employee_Survey_Data_1_$`Years Worked`)
```

#Graphs for Each Category

```{r}
boxplot.stats(Typical_Employee_Survey_Data_1_$Age)
boxplot.stats(Typical_Employee_Survey_Data_1_$`Years Worked`)
boxplot(Typical_Employee_Survey_Data_1_$Age)
hist(Typical_Employee_Survey_Data_1_$Age)
barplot(table(Typical_Employee_Survey_Data_1_$Gender))
barplot(table(Typical_Employee_Survey_Data_1_$Satisfaction))
barplot(table(Typical_Employee_Survey_Data_1_$Characteristics))
hist(Typical_Employee_Survey_Data_1_$`Years Worked`)
barplot(table(Typical_Employee_Survey_Data_1_$`Promotion Likelihood`))
barplot(table(Typical_Employee_Survey_Data_1_$`Decision-Making`))
barplot(table(Typical_Employee_Survey_Data_1_$`Budgetary Decisions`))
barplot(table(Typical_Employee_Survey_Data_1_$Pride))
barplot(table(Typical_Employee_Survey_Data_1_$'Reject Other Jobs'))
pie(table(Typical_Employee_Survey_Data_1_$Relations))
```


#Plots Showing Different Relationships
```{r}
plot(Typical_Employee_Survey_Data_1_$Age,Typical_Employee_Survey_Data_1_$`Years Worked`, main="Age & Years Worked", xlab="Age", ylab="Years Worked")

plot(Typical_Employee_Survey_Data_1_$Satisfaction, Typical_Employee_Survey_Data_1_$`Reject Other Jobs`, main="Satisfaction vs Likelihood to Reject Other Jobs", xlab="Satisfaction",ylab="Likelihood to Reject Other Jobs")

plot(Typical_Employee_Survey_Data_1_$`Years Worked`,
jitter(as.numeric(Typical_Employee_Survey_Data_1_$Satisfaction)),
main = "Years Worked vs Satisfaction",
xlab = "Years Worked",
ylab = "Satisfaction")

plot(Typical_Employee_Survey_Data_1_$Age,
jitter(as.numeric(Typical_Employee_Survey_Data_1_$`Promotion Likelihood`)),
main = "Age vs Promotion Likelihood",
xlab = "Age",
ylab = "Promotion Likelihood")

```

